import json
from pathlib import Path

from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    VectorParams,
    PointStruct
)


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

# Input generated by cobol_context_extractor.py
JSON_FILE = BASE_DIR / "cobol_enriched_chunks.json"

# Qdrant database location
QDRANT_PATH = BASE_DIR / "qdrant_storage"

# Qdrant collection
COLLECTION_NAME = "cobol_code_chunks"

# Embedding model
MODEL_NAME = "all-MiniLM-L6-v2"


# ============================================================
# 1. LOAD COBOL CHUNKS
# ============================================================

print("\n========================================")
print("COBOL VECTOR STORE CREATION")
print("========================================")

if not JSON_FILE.exists():
    raise FileNotFoundError(
        f"Chunk JSON not found: {JSON_FILE}"
    )

with open(JSON_FILE, "r", encoding="utf-8") as f:
    chunks = json.load(f)

print("Chunks loaded:", len(chunks))

if not chunks:
    raise ValueError("No chunks found in JSON file.")


# ============================================================
# 2. LOAD EMBEDDING MODEL
# ============================================================

print("\nLoading embedding model...")

model = SentenceTransformer(MODEL_NAME)

# all-MiniLM-L6-v2 produces 384-dimensional embeddings
VECTOR_SIZE = model.get_embedding_dimension()

print("Embedding model:", MODEL_NAME)
print("Vector dimensions:", VECTOR_SIZE)


# ============================================================
# 3. CONNECT TO LOCAL QDRANT
# ============================================================

print("\nOpening Qdrant vector database...")

client = QdrantClient(
    path=str(QDRANT_PATH)
)

print("Qdrant storage:", QDRANT_PATH)


# ============================================================
# 4. CREATE COLLECTION
# ============================================================

if not client.collection_exists(COLLECTION_NAME):

    print("\nCreating collection:", COLLECTION_NAME)

    client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(
            size=VECTOR_SIZE,
            distance=Distance.COSINE
        )
    )

    print("Collection created.")

else:

    print("\nCollection already exists:", COLLECTION_NAME)


# ============================================================
# 5. PREPARE CHUNK TEXT
# ============================================================

print("\nPreparing chunks for embedding...")

texts = []

for chunk in chunks:

    operations = ", ".join(
        chunk.get("operations", [])
    )

    variables = ", ".join(
        chunk.get("variables", [])
    )

    text = f"""
Source Type: {chunk.get('source_type', '')}
File Name: {chunk.get('file_name', '')}
Program: {chunk.get('program', '')}
Section: {chunk.get('section', '')}
Paragraph: {chunk.get('paragraph', '')}
Operations: {operations}
Variables: {variables}

COBOL CODE:
{chunk.get('code', '')}
""".strip()

    texts.append(text)

print("Chunks prepared:", len(texts))


# ============================================================
# 6. GENERATE EMBEDDINGS
# ============================================================

print("\nGenerating embeddings...")

embeddings = model.encode(
    texts,
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Embeddings generated:", len(embeddings))
print("Embedding dimensions:", embeddings.shape[1])


# ============================================================
# 7. PREPARE QDRANT POINTS
# ============================================================

print("\nPreparing Qdrant points...")

points = []

for index, (chunk, embedding) in enumerate(
    zip(chunks, embeddings)
):

    point = PointStruct(

        id=index,

        # 384 floating-point values
        vector=embedding.tolist(),

        # Original information is kept as payload
        payload={
            "source_type": chunk.get(
                "source_type", ""
            ),

            "file_name": chunk.get(
                "file_name", ""
            ),

            "program": chunk.get(
                "program", ""
            ),

            "section": chunk.get(
                "section", ""
            ),

            "paragraph": chunk.get(
                "paragraph", ""
            ),

            "operations": chunk.get(
                "operations", []
            ),

            "variables": chunk.get(
                "variables", []
            ),

            "code": chunk.get(
                "code", ""
            )
        }
    )

    points.append(point)

print("Points prepared:", len(points))


# ============================================================
# 8. STORE IN QDRANT
# ============================================================

print("\nStoring vectors in Qdrant...")

client.upsert(
    collection_name=COLLECTION_NAME,
    points=points,
    wait=True
)

print("Vectors stored successfully.")


# ============================================================
# 9. VERIFY STORAGE
# ============================================================

collection_info = client.get_collection(
    COLLECTION_NAME
)

print("\n========================================")
print("VECTOR STORAGE COMPLETED")
print("========================================")

print("Chunks processed:", len(chunks))
print("Vectors stored:", collection_info.points_count)
print("Vector dimensions:", VECTOR_SIZE)
print("Collection:", COLLECTION_NAME)
print("Database location:", QDRANT_PATH)

print("========================================")


# ============================================================
# 10. CLOSE QDRANT
# ============================================================

client.close()